#! /bin/sh

sxhkd &
picom &
dunst &
polybar bar &
wal -i "$HOME/wallpaper.jpg"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.53
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a vlc state=floating
